---
title: "SQL Interview"
date-format: long
format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    embed-resources: true
    number-sections: true
author:
  - name: 
---


# Requirement
You will have 25 minutes to work on the following 8 questions:
If you don’t have time to write down the complete query, try to write down the steps of your thought process. If you feel the time is tight, focus more on questions 1~6. We put the needed data table(s) before each question and removed certain variables for simplicity. The data in the table are not limited to the rows demonstrated as examples. Please feel free to use MySQL, Oracle SQL, PostgreSQL, MS SQL, Bigquery or any other SQL syntax you feel comfortable with.


# Table Overview
There are three tables available: 

*   **Orders:** Transactional table which shows offer details of car rental bookings. Each row represents each order 
       + **offer_id:** unique identifier of each booked rental car
       + **total_price:** the total rate charged on the customer with margin
       + **base_price:** the total rate given by the suppliers without margin
       + **length_of_keep:** number of days cars being rented
       + **location_code:** the location where cars to be picked up
       + **vehicle_code:** the car type that is booked
       + **offer_date_time:** date-time when offer is booked

|  offer_id | supplier_code | total_price | base_price | length_of_keep | location_code | vehicle_code |   offer_date_time   |   offer_status  |
|-----------|---------------|-------------|------------|----------------|---------------|--------------|---------------------|-----------------|
|   10001   |      AV       |     80.5    |    64.5    |      1         |      MCO      |     CCAR     | 2024-01-02 12:01:01 |    0_ACCEPTED   |
|   100021  |      BU       |     70.9    |    60.4    |      1         |      LGA      |     FCAR     | 2024-01-02 13:02:10 |    0_ACCEPTED   |     
|   30358   |      HZ       |    201.3    |    177.1   |      3         |      BOS      |     SPAR     | 2024-01-10 13:11:23 |    0_REJECTED   |
|   1009485 |      ZR       |    222.7    |    190     |      4         |      DEN      |     SFAR     | 2024-01-01 09:13:27 |    0_ACCEPTED   |
|   204531  |      ET       |    304.2    |    234.2   |      4         |      LGA001   |     FFAR     | 2024-01-11 10:11:00 |    0_CANCELLED  |
|   20003   |      BU       |    594.9    |    510.3   |      7         |      MIA      |     ICAR     | 2024-01-23 04:50:11 |    0_ACCEPTED   |
: Orders {.striped .hover}

*   **Suppliers:** Dimensional table that maps the brand names by supplier_code
       + **supplier_id:** supplier is the brand of the rental car company booked
       + **supplier_name:** brand name of the supplies

|  supplier_code | supplier_name | num_active_locations | opaque_participant_flag |
|----------------|---------------|----------------------|-------------------------|
|       AV       |      Avis     |         200          |            Y            |
|       BU       |      Budget   |         202          |            Y            |
|       AL       |      Alamo    |         307          |            Y            |
|       AC       |      ACE      |         131          |            Y            |
|       FO       |      Foco     |         40           |            N            |
: Suppliers {.striped .hover}

*   **Location:** Dimensional table that shows location details
       + **location_code:** the location where cars to be picked up
       + **airport_code:** corresponding airport of the pickup location
       + **city_name:** corresponding city of the pickup location

|  location_code |   city_name   | on_airport_flag |
|----------------|---------------|-----------------|
|     MCO001     |   Orlando     |        N        |
|     NYC002     |   New York    |        N        |
|     AUS        |   Austin      |        Y        |
|     DFW        |   Dallas      |        Y        |
|     LGA        |   New York    |        Y        |
|     ATL        |   Atlanta     |        Y        |
: Loctions {.striped .hover}


# Question 1
Write a SQL query to calculate number of bookings by date

```{sql}

```

# Question 2
Write a SQL query to get number of bookings for January by supplier names 
```{sql}

```

# Question 3
Write a SQL query to count how many distinct vehicle types booked in each location
```{sql}

```

# Question 4
Write a SQL query to display average offer total price from highest to lowest by city names
```{sql}

```

# Question 5
Write a SQL query to count percentaage of bookings where the margin% is less than 10% 
```{sql}

```